In [24]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
data = pd.read_csv("creditcard.csv")

In [26]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [27]:
data.shape

(284807, 31)

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [29]:
data.isnull().values.any()

False

In [30]:
fraud = data[data['Class']==1]
non_fraud = data[data['Class']==0]

In [32]:
fraud.shape, non_fraud.shape

((492, 31), (284315, 31))

In [33]:
non_fraud_t = non_fraud.sample(492)

In [35]:
non_fraud_t.shape

(492, 31)

In [40]:
data = pd.concat([fraud, non_fraud_t], ignore_index=True)


In [45]:
data["Class"].value_counts()

Class
1    492
0    492
Name: count, dtype: int64

In [42]:
data.shape

(984, 31)

In [47]:
X = data.drop(labels = ["Class"], axis = 1)
y = data["Class"]

In [51]:
X.shape, y.shape

((984, 30), (984,))

In [49]:
from sklearn.model_selection import train_test_split

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size =0.2, random_state=0)

In [53]:
X_test.shape, X_train.shape, y_test.shape, y_train.shape

((197, 30), (787, 30), (197,), (787,))

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

In [56]:
X_train, X_test

(array([[-0.62803198, -1.12999563, -3.55433842, ...,  1.51072144,
         -1.55068924, -0.35357125],
        [-0.78199142,  0.50909422, -0.08510731, ...,  0.47296597,
          0.61226534, -0.43045089],
        [-0.81833043,  0.18896123,  0.10854434, ...,  0.3132522 ,
          0.46739567, -0.42949189],
        ...,
        [-0.06770648,  0.09585603, -0.23938577, ..., -0.28820887,
         -0.68628929, -0.33239339],
        [ 0.66954127,  0.80057135, -0.58268518, ..., -0.2256358 ,
         -0.19615959, -0.22310762],
        [ 0.60331577,  0.28203559, -0.18584419, ..., -0.07018864,
          0.09679718, -0.43348771]]),
 array([[-0.36341676,  0.6715529 , -0.64518587, ..., -0.03520295,
          0.01831333, -0.35520954],
        [ 1.38087648, -0.05002155, -0.61261972, ..., -0.33882911,
         -0.61927039,  0.41606425],
        [-1.53564704,  0.17397058,  0.67342997, ...,  2.06502902,
          1.55418944, -0.42949189],
        ...,
        [-1.47376419, -0.44049852,  1.93675651, ...,  

In [57]:
y_train = y_train.to_numpy()

In [58]:
y_test = y_test.to_numpy()

In [59]:
y_test, y_train

(array([1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0],
       dtype=int64),
 array([0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        1, 1, 0, 1,

In [60]:
X_train = X_train.reshape(787, 30, 1)
X_test = X_test.reshape(197, 30, 1)

In [61]:
X_train.shape, X_test.shape

((787, 30, 1), (197, 30, 1))

In [82]:
model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(30,1)),
    tf.keras.layers.Conv1D(filters = 32, kernel_size =3, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPool1D(pool_size=2),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Conv1D(filters = 64, kernel_size = 3, activation='relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.MaxPool1D(pool_size=2),
    tf.keras.layers.Dropout(0.4),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units = 64, activation='relu'),
    tf.keras.layers.Dense(units =1, activation='sigmoid')
])

In [83]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_10 (Conv1D)              │ (None, 28, 32)         │           128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_10          │ (None, 28, 32)         │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_10 (MaxPooling1D) │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 14, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_11 (Conv1D)              │ (None, 12, 64)         │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_11          │ (None, 12, 64)         │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_11 (MaxPooling1D) │ (None, 6, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_11 (Dropout)            │ (None, 6, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 384)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │        24,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,425 (122.75 KB)

 Trainable params: 31,233 (122.00 KB)

 Non-trainable params: 192 (768.00 B)

In [84]:
opt = tf.keras.optimizers.Adam(learning_rate=0.00005)
model.compile(optimizer=opt, loss = 'binary_crossentropy', metrics= ['accuracy'])

In [86]:
model.fit(X_train, y_train, epochs =20 , validation_data=(X_test, y_test))

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8761 - loss: 0.3051 - val_accuracy: 0.9188 - val_loss: 0.2166
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8931 - loss: 0.2767 - val_accuracy: 0.9188 - val_loss: 0.2091
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8995 - loss: 0.2778 - val_accuracy: 0.9188 - val_loss: 0.2031
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8871 - loss: 0.2885 - val_accuracy: 0.9188 - val_loss: 0.1972
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9005 - loss: 0.2513 - val_accuracy: 0.9239 - val_loss: 0.1922
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8964 - loss: 0.2665 - val_accuracy: 0.9289 - val_loss: 0.1886
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9020 - loss: 0.2694 - val_accuracy: 0.9289 - val_loss: 0.1863
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8991 - loss: 0.2684 - val_accuracy: 0.9289 - val_loss:

In [87]:
y_pred = (model.predict(X_test)>0.5).astype('int64')

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [90]:
y_pred[10], y_test[10]

(array([0], dtype=int64), 1)

In [91]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [92]:
confusion_matrix(y_test, y_pred)

array([[106,   0],
       [ 13,  78]], dtype=int64)

In [93]:
accuracy_score(y_test, y_pred)

0.934010152284264